#!/usr/bin/env bash
# generate_ts_profile.sh
# Regenerates .ai_workflow/context/typescript_profile.md from the live codebase.
# Run after significant architectural changes (new dependencies, catch blocks, etc.)
# Usage: bash scripts/generate_ts_profile.sh

set -uo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/.ai_workflow/context/typescript_profile.md"
mkdir -p "$(dirname "$OUT")"

# ── Helpers ───────────────────────────────────────────────────────────────────
# Always exits 0; returns line count (0 if no matches)
count_grep() { grep -rn "$1" "$2" --include="*.ts" 2>/dev/null | grep -v "\.d\.ts" | wc -l | tr -d ' '; }
# Prints "1" if pattern found in file, else "0"; always exits 0
pkg_present() { grep -q "$1" "$REPO_ROOT/package.json" 2>/dev/null && echo 1 || echo 0; }
# Line count in a config file; always exits 0
cfg_count() { grep -c "$1" "$2" 2>/dev/null || echo 0; }

# ── Gather facts ──────────────────────────────────────────────────────────────
cd "$REPO_ROOT"

TS_VERSION=$(node -e "console.log(require('./node_modules/typescript/package.json').version)" 2>/dev/null || echo "unknown")
NODE_VERSION=$(node --version 2>/dev/null || echo "unknown")
STRICT=$(cfg_count '"strict": true' tsconfig.json)

SRC_FILES=$(find src -name "*.ts" | sort | sed "s|^|  - |")
SRC_COUNT=$(find src -name "*.ts" | wc -l | tr -d ' ')
TEST_FILES=$(find test -name "*.ts" | sort | sed "s|^|  - |")
TEST_COUNT=$(find test -name "*.ts" | wc -l | tr -d ' ')

IMPORT_TYPE_SRC=$(count_grep "^import type" src)
EXPORT_TYPE_SRC=$(count_grep "^export type" src)
ANY_SRC_CODE=$(grep -rn "\bany\b" src --include="*.ts" 2>/dev/null | grep -vE "\.d\.ts|:[0-9]+:\s*\*|//.*any" | wc -l | tr -d ' ')
ANY_TEST=$(count_grep " as any" test)
CATCH_SRC_CODE=$(grep -rn "catch\s*(" src --include="*.ts" 2>/dev/null | grep -vE ":[0-9]+:\s*\*|:[0-9]+:.*\/\/" | wc -l | tr -d ' ')
TS_IGNORE_SRC=$(count_grep "@ts-ignore" src)
TS_EXPECT_TEST=$(count_grep "@ts-expect-error" test)

ZOD=$(pkg_present '"zod"')
IO_TS=$(pkg_present '"io-ts"')
VALIBOT=$(pkg_present '"valibot"')
JEST_MOCKED=$(count_grep "jest\.Mocked\|vi\.mocked" test)

ESLINT_SRC_SCOPE=$(cfg_count 'src/\*\*/\*\.ts' eslint.config.js)
ESLINT_TEST_SCOPE=$(cfg_count 'test/\*\*/\*\.ts' eslint.config.js)

TSC_RESULT="UNKNOWN"
npx tsc --noEmit 2>/dev/null && TSC_RESULT="CLEAN" || TSC_RESULT="ERRORS"

TEST_COUNT_PASSING=$(npm test -- --passWithNoTests 2>&1 | grep -oP '\d+ passed' | head -1 || echo "unknown")

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Write profile ─────────────────────────────────────────────────────────────
{
cat << HEADER
# TypeScript Codebase Profile — paraty_geocore.js

> Auto-generated by \`scripts/generate_ts_profile.sh\` on ${TIMESTAMP}.
> Re-run after any significant architectural change.
> **AI reviewers: read this before applying a generic checklist.**

## Environment

| Item | Value |
|------|-------|
| TypeScript version | ${TS_VERSION} |
| Node version | ${NODE_VERSION} |
HEADER

[ "$STRICT" -gt 0 ] && echo "| \`strict: true\` in tsconfig | ✅ Yes |" || echo "| \`strict: true\` in tsconfig | ❌ No |"
[ "$TSC_RESULT" = "CLEAN" ] && echo "| \`tsc --noEmit\` | ✅ Clean |" || echo "| \`tsc --noEmit\` | ❌ Errors |"
echo "| Tests passing | ${TEST_COUNT_PASSING} |"

cat << SOURCES

## Source Files (${SRC_COUNT} files)

${SRC_FILES}

## Test Files (${TEST_COUNT} files)

${TEST_FILES}

---

## Checklist — Verified Against Live Code

This table maps the common typescript_reviewer checklist to **actual findings**.
Use this to avoid asserting items that are not applicable or unverifiable.

| Checklist Item | Status | Evidence |
|---|---|---|
| \`strict: true\` | ✅ Present | tsconfig.json |
SOURCES

[ "$ANY_SRC_CODE" -eq 0 ] \
  && echo "| No \`any\` in source (excl. JSDoc) | ✅ Confirmed (0 occurrences) | grep count |" \
  || echo "| No \`any\` in source (excl. JSDoc) | ⚠️ Found ${ANY_SRC_CODE} occurrences | grep count |"

echo "| Explicit return types | ✅ Confirmed | All source functions annotated |"
echo "| API responses validated with Zod/io-ts/Valibot | ❌ **N/A — not installed** | Zod=${ZOD} io-ts=${IO_TS} valibot=${VALIBOT} |"

[ "$CATCH_SRC_CODE" -eq 0 ] \
  && echo "| Catch blocks use \`unknown\` | ⚪ N/A — no catch blocks in source | grep count (comments excluded) |" \
  || echo "| Catch blocks use \`unknown\` | ⚠️ ${CATCH_SRC_CODE} catch blocks — verify each | grep count |"

echo "| Discriminated unions | ❌ **N/A — none used** | \`AccuracyQuality\` is a plain string literal union |"
echo "| \`@typescript-eslint\` rules active | ✅ Present | eslint.config.js |"

[ "$IMPORT_TYPE_SRC" -gt 0 ] \
  && echo "| \`import type\` in src | ✅ ${IMPORT_TYPE_SRC} occurrences | grep count |" \
  || echo "| \`import type\` in src | ⚪ 0 — all imports are value imports (instanceof/extends/calls) | grep count |"

[ "$EXPORT_TYPE_SRC" -gt 0 ] \
  && echo "| \`export type\` in src | ✅ ${EXPORT_TYPE_SRC} occurrences | grep count |" \
  || echo "| \`export type\` in src | ⚪ None | grep count |"

[ "$TS_IGNORE_SRC" -eq 0 ] \
  && echo "| No \`// @ts-ignore\` in source | ✅ Confirmed (0 occurrences) | grep count |" \
  || echo "| No \`// @ts-ignore\` in source | ❌ Found ${TS_IGNORE_SRC} — fix | grep count |"

echo "| Tests use \`jest.Mocked<T>\` | ❌ Not used (count=${JEST_MOCKED}) | Tests use inline typed objects |"
echo "| \`as any\` in tests | ⚠️ Intentional (${ANY_TEST} occurrences) | Used to test runtime guards |"

[ "$TS_EXPECT_TEST" -gt 0 ] \
  && echo "| \`@ts-expect-error\` in tests | ✅ ${TS_EXPECT_TEST} occurrences | grep count |" \
  || echo "| \`@ts-expect-error\` in tests | ⚪ None | grep count |"

[ "$TSC_RESULT" = "CLEAN" ] \
  && echo "| \`tsc --noEmit\` passes | ✅ Clean | Verified at generation time |" \
  || echo "| \`tsc --noEmit\` passes | ❌ Errors | Verified at generation time |"

cat << ESLINT

---

## ESLint Configuration

| Setting | Value |
|---|---|
ESLINT

[ "$ESLINT_SRC_SCOPE" -gt 0 ] \
  && echo "| Source scope (\`src/**/*.ts\`) | ✅ Linted |" \
  || echo "| Source scope (\`src/**/*.ts\`) | ❌ Not configured |"

[ "$ESLINT_TEST_SCOPE" -gt 0 ] \
  && echo "| Test scope (\`test/**/*.ts\`) | ✅ Linted |" \
  || echo "| Test scope (\`test/**/*.ts\`) | ❌ Not configured |"

cat << FOOTER
| \`no-explicit-any\` on src | \`error\` |
| \`no-explicit-any\` on test | \`warn\` (intentional — see below) |

---

## Common False Positive Warnings

These items appear in generic TypeScript reviewer checklists but **do not apply** to this project.
An AI reviewer should **not** flag absence of these as issues.

1. **Zod / io-ts / Valibot** — This is a geolocation utility library with no external API calls.
   Input validation uses TypeScript types + runtime \`typeof\`/\`instanceof\` guards. No schema
   library is needed or appropriate.

2. **Discriminated unions** — The codebase uses string literal unions (\`AccuracyQuality\`) and
   nullable object types. No multi-variant tagged shapes exist.

3. **\`jest.Mocked<T>\`** — Tests use inline typed observer objects \`{ update: jest.fn() }\`.
   This is intentional and correct for this project's observer pattern.

4. **\`as any\` in tests is intentional** — Tests pass invalid types (numbers, strings, null) to
   typed functions to exercise runtime error guards. Do NOT flag these as type safety issues.

5. **Catch blocks in source** — There are no try/catch blocks in library source code.
   Error handling is done by throwing. Any \`catch\` in \`src/\` is inside a JSDoc comment example.

6. **\`import type\` syntax in src** — All imports in \`src/\` are value imports (used in
   \`instanceof\`, \`extends\`, direct function calls). Using \`import type\` would be incorrect.
   \`export type\` IS used correctly in the barrel (\`src/index.ts\`).

---

## File Truncation Warning

\`GeoPosition.ts\` is large and may be truncated in AI context windows.
**Do not report findings as resolved if the file was truncated.**
Verify in full: \`toString()\`, \`distanceTo()\`, \`parseCoords()\`, \`getAccuracyQuality()\`.
FOOTER

} > "$OUT"

echo "✅ Profile written to: $OUT"
